steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/lam:latest', './backend']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/lam:latest']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'lam'
    - '--image'
    - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/lam:latest'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    - '--port'
    - '8080'
    - '--allow-unauthenticated'

images:
- europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/lam:latest 