[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[variables]
PYTHON_VERSION = "3.11"

[deploy]
startCommand = "uvicorn server:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"

[env]
PORT = "8000"
ENVIRONMENT = "production" 