[providers]
python = "3.11"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
PLAYWRIGHT_BROWSERS_PATH = "/nix/store"

[phases.setup]
nixPkgs = ["python311", "nodejs_18", "chromium"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "playwright install chromium --with-deps"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python -m uvicorn server:app --host 0.0.0.0 --port $PORT" 