[build]
builder = "nixpacks"

[deploy]
startCommand = "python -m uvicorn server:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PYTHONPATH = "/app"
PLAYWRIGHT_BROWSERS_PATH = "/usr/lib/playwright"
PLAYWRIGHT_HEADLESS = "true" 