[build]
builder = "nixpacks"

[deploy]
startCommand = "bash start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_VERSION = "18"
PYTHON_VERSION = "3.11"
PORT = "8000"
PYTHONPATH = "." 