name: Deploy AI LAM

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Clean and install frontend dependencies
        run: |
          cd frontend
          rm -f package-lock.json
          npm install
          
      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements-core.txt
          
      - name: Run frontend tests (basic check)
        run: |
          cd frontend
          npm run build
          
      - name: Check backend syntax
        run: |
          cd backend
          python -m py_compile server.py

  deploy-frontend:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./frontend

  # Backend deployment to Fly.io is done manually
  # You can add a Fly.io deployment action here if you want automatic deployment 